### ISSUE TITLE
what is initrd? 

### ISSUE THREAD

**Issue by De4dCr0w** [SmoothHacker/LateRegistration#6]
What file is initrd and what is the content? Could you give a working example?

**Comment by SmoothHacker** [comment]
Initrd is the initial root file system that is mounted prior to when the real root file system is available. It's not in this repo. I have one locally that I created using busybox and a normal C program acting as the init process. I think you should be able to not use busybox entirely. I will have a guide accompanying the repo sometime soon about how others can make their own initrd.
